#########################################################
# LUET
#########################################################
luet_version: 0.32.4

#########################################################
# Slicer-related variables
#########################################################
slicer_url: "https://github.com/Slicer/Slicer.git"
slicer_branch: "main"
slicer_testing: "ON"
slicer_build: "Release"

#########################################################
# Compilation-related variables
#########################################################
jobs: 1
