{{ $distro_tag := ( regexSplit ".*_" .Values.name -1 | last ) }}
{{ $distro_name  := .Values.category }}

requires:
  - name: "OSBase_{{ regexSplit ".*_" .Values.name -1 | last }}"
    category: "{{ .Values.category }}"
    version: "{{ .Values.version }}"
env:
  - DEBIAN_FRONTEND=noninteractive
steps:
  # Install system requirements -- if any
  {{ if ( index .Values.labels "system.build_requirements" ) }}
    {{ if eq $distro_name "archlinux" }}
      {{ template "archlinux-install" ( index .Values.labels "system.build_requirements" ) }}
    {{ end }}
    {{ if eq $distro_name "ubuntu" }}
      {{ template "ubuntu-install" ( index .Values.labels "system.build_requirements" ) }}
    {{ end }}
  {{ end }}
  # Install qt dependencies
  {{ if ( index .Values.labels "system.qt_requirements" ) }}
    {{ if eq $distro_name "archlinux" }}
      {{ template "archlinux-install" ( index .Values.labels "system.qt_requirements" ) }}
    {{ end }}

    {{ if eq $distro_name "ubuntu" }}
      {{ template "ubuntu-install" ( index .Values.labels "system.qt_requirements" ) }}
    {{ end }}
  {{ end }}
  # Install testing dependencies
  {{ if and ( index .Values.labels "system.testing_requirements" ) (eq .Values.slicer_testing "ON") }}
    {{ if eq $distro_name "archlinux" }}
      {{ template "archlinux-install" ( index .Values.labels "system.testing_requirements" ) }}
    {{ end }}

    {{ if eq $distro_name "ubuntu" }}
      {{ template "ubuntu-install" ( index .Values.labels "system.testing_requirements" ) }}
    {{ end }}
  {{ end }}
  {{ if eq .Values.labels.systemcmake "no" }}
  {{ template "cmake-install" "3.25.1" }}
  {{ end }}
  - curl https://luet.io/install.sh | LUET_VERSION={{ .Values.luet_version }} sh
  - cp slicerbuildfactory.yaml /etc/luet/repos.conf.d
  - ln -s /usr/bin/ccache /usr/local/bin/c++
  - ln -s /usr/bin/ccache /usr/local/bin/cc
