{{ $distro_tag := ( regexSplit ".*_" .Values.name -1 | last ) }}
{{ $distro_name  := .Values.category }}

requires:
  - name: "SlicerBuildEnvironment_{{ regexSplit ".*_" .Values.name -1 | last }}"
    category: "{{ .Values.category }}"
    version: "{{ .Values.version }}"

excludes:
  - .*

prelude:
  - curl https://luet.io/install.sh | sh
  - cp slicerbuildfactory.yaml /etc/luet/repos.conf.d

steps:
  {{ if eq $distro_name "archlinux" }}
    {{ template "archlinux-install" "ccache" }}
  {{ end }}

  {{ if eq $distro_name "ubuntu" }}
    {{ template "ubuntu-install" "ccache" }}
  {{ end }}

  - ln -s /usr/bin/ccache /usr/local/bin/c++
  - ln -s /usr/bin/ccache /usr/local/bin/cc
