requires:
  - name: "SlicerBuildEnvironment_jammy"
    category: "{{ .Values.category }}"
    version: "0.1"
env:
  - CCACHE_DIR=/var/cache/SlicerBuildFactory/{{ .Values.category }}/{{ .Values.name }}
  - CCACHE_COMPILERCHECK=content
  - CCACHE_LOGFILE=/var/log/ccache
  - CCACHE_SLOPPINESS=include_file_ctime,include_file_mtime
steps:
  - luet repo update || echo "No repo available"
  - luet install {{ .Values.category }}/Slicer_ccache_{{ regexSplit ".*_" .Values.name -1 | last }} -y || echo "No ccache available"
  - mkdir -p ${CCACHE_DIR}
  # Get the source code
  - git clone https://github.com/kitware/vtk vtk --depth 1
  - cd vtk && git checkout master
  # Configure project
  - mkdir vtk/Release -p
  - cd vtk/Release && cmake -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_TESTING:BOOL=OFF ../ -DCMAKE_C_COMPILER=/usr/local/bin/cc -DCMAKE_CXX_COMPILER=/usr/local/bin/c++
  # Build the project
  - cd vtk/Release && make -j{{ .Values.jobs }}
  - cd vtk/Release && make install
excludes:
  - /luetbuild$
subpackages:
  - name: "VTK_ccache_{{ regexSplit ".*_" .Values.name -1 | last }}"
    category: "{{ .Values.category }}"
    version: "0.1"
    includes:
      - /var$
      - /var/cache$
      - /var/cache/SlicerBuildFactory$
      - /var/cache/SlicerBuildFactory/{{ .Values.category }}$
      - /var/cache/SlicerBuildFactory/{{ .Values.category }}/{{ .Values.name }}$
      - /var/cache/SlicerBuildFactory/{{ .Values.category }}/{{ .Values.name }}/.*
